# Generated by Django 5.2.15 on 2026-06-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal', 'Proposal Sent'), ('won', 'Won'), ('lost', 'Lost'), ('cancelled', 'Cancelled')], default='new', max_length=20),
        ),
    ]
